- name: Ensure all necesary group are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - adm

- name: Ensure the non-root user is created
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('bcrypt')}}" # crypta la password con bcrypt così da non lasciare traccia nel SO della password reale
    # la password si trova nel vault dei singoli host sotto host_vars
    groups:
      - sudo
      - docker
      - users
      - adm
    append: yes
    shell: "{{ shell }}"
    update_password: on_create

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
    
